services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: server
    container_name: server
    ports:
      - "8000:8000"
    env_file:
      - ./development.env
    depends_on:
      - db
    volumes:
      - ./server:/app
   
  client: 
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    

  db:
    image: postgres:13
    container_name: db
    env_file:
      - ./development.env
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

volumes:
  postgres_data: