FROM python:3.11.3-alpine3.17

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN python3 -m pip install -U --upgrade pip

RUN pip3 install -U --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--root-path", "/", "--reload"]